### ISSUE TITLE
Introduce commands for managing templates using the plugin

### ISSUE THREAD

**Issue by hexdigest** [hexdigest/gounit-vim#2]
It would be nice to have GoUnitTemplateAdd, GoUnitTemplateDel, GoUnitTemplateEdit, GoUnitTemplateUse commands provided by the plugin

**Comment by ipriver** [comment]
@hexdigest check https://github.com/hexdigest/gounit-vim/tree/tmplcmds branch
+ GoUnitTemplateAdd - if no arguments provided uses your current buffer file as a new template, or you should give path for template file as an argument
+ GoUnitTemplateList - lists all installed templates
+ GoUnitTemplateDel - removes template by its name in gounit list
+ GoUnitTemplateUse - is an alternative for GoUnit <template_name>, simply changes current template, but doesn't generate tests (GoUnit does it)
- GoUnitTemplateEdit - no such functionality in gouinit yet, so it cannot be implemented

**Comment by hexdigest** [comment]
Thanks @ipriver !
